apiVersion: v1
kind: Template
labels:
  template: test-configmap-template
message: "Deploying using templated resources"
metadata:
  name:  configmap-template
objects:
- apiVersion: v1
  kind: ConfigMap
  data:
    cgroup: cgroup
    topicname: ${TOPIC_NAME}
    patchOverride: ${PATCH_OVERRIDE}
  metadata:
    name: ${APP_NAME}
############################################
parameters:
- description: The name for the microservice
  displayName: Microservice Name
  name: APP_NAME
  required: true

- description: A topic name
  name: TOPIC_NAME
  required: true

- description: A patch override test
  name: PATCH_OVERRIDE
  required: false
  value: "THE TEST WORKED!!!"
