apiVersion: v1
kind: Template
labels:
  template: dc-svc-template
message: Deploying using templated resources
metadata:
  name:  dc-svc-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    replicas: ${{REPLICAS}}
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      type: ${STRATEGY}
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
          - name: ${APP_NAME}
            image: ${IMAGE_REPOSITORY}/${PROJECT_ID}-${MICROSERVICE_NAME}:${IMAGE_TAG}
            imagePullPolicy: Always
            resources:
              limits:
                cpu: ${CPU_LIMIT}
                memory: ${MEM_LIMIT}
              requests:
                cpu: ${CPU_REQ}
                memory: ${MEM_REQ}
            ports:
            - containerPort: ${{SVC_PORT}}
              protocol: TCP
        imagePullSecrets:
          - name: ${PULL_SECRET}
    triggers: []
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    selector:
      app: ${APP_NAME}
    ports:
      - protocol: TCP
        port: ${{SVC_PORT}}
        targetPort: ${{SVC_PORT}}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    host: ${APP_NAME}-${ENV}.${CLUSTER_WILDCARD_DOMAIN}
    port:
      targetPort: ${{SVC_PORT}}
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
############################################
parameters:
- description: The cluster wildcard domain
  displayName: Cluster Wildcard Domain
  name: CLUSTER_WILDCARD_DOMAIN
  required: true

- description: The image repository where the image to be deployed exists
  displayName: Image Repository
  name: IMAGE_REPOSITORY
  required: true

- description: The image repository where the image to be deployed exists
  displayName: Image Repository
  name: PULL_SECRET
  required: true

- description: The name for the microservice
  displayName: Microservice Name
  name: MICROSERVICE_NAME
  required: true

- description: The name for the application
  displayName: Application Name
  name: APP_NAME
  required: true

- description: The Project ID
  displayName: Project ID
  name: PROJECT_ID
  required: true

- description: The name of the environment.
  displayName: Environment Name
  name: ENV
  required: true

- description: Artifactory Docker Image Tag
  displayName: Artifactory Docker Image Tag
  name: IMAGE_TAG
  required: true

- description: CPU Resource Request (Floor) in millicores
  displayName: CPU Resource Request in millicores
  name: CPU_REQ
  required: true
  value: 100m

- description: CPU Resource Limit (Ceiling) in millicores
  displayName: CPU Resource Limit in millicores
  name: CPU_LIMIT
  required: true
  value: 200m

- description: Memory Resource Request (Floor) in Mi or Gi
  displayName: Memory Resource Request in Mi or Gi
  name: MEM_REQ
  required: true
  value: 50Mi

- description: Memory Resource Limit (Ceiling) in Mi or Gi
  displayName: Memory Resource Limit in Mi or Gi
  name: MEM_LIMIT
  required: true
  value: 500Mi

- description: The number of replicas for this deployment
  displayName: Replica count
  name: REPLICAS
  value: "1"

- description: Service port
  displayName: Service Port
  name: SVC_PORT
  required: true
  value: "8080"

- description: Deployment strategy
  displayName: Deployment strategy
  name: STRATEGY
  required: true
  value: Rolling
